import { Extension } from "../../../common"
import { OAuthFlowsObject } from "./OAuthFlowsObject"

/**
 * Defines a security scheme that can be used by the operations.
 *
 * Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter or as a query parameter), mutual TLS (use of a client certificate), OAuth2’s common flows (implicit, password, client credentials and authorization code) as defined in {@link https://spec.openapis.org/oas/v3.1.0#bib-RFC6749 [RFC6749]}, and {@link https://datatracker.ietf.org/doc/html/draft-ietf-oauth-discovery-06 OpenID Connect Discovery}. Please note that as of 2020, the implicit flow is about to be deprecated by {@link https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics OAuth 2.0 Security Best Current Practice}. Recommended for most use case is Authorization Code Grant flow with PKCE.
 * @link https://spec.openapis.org/oas/v3.1.0#security-scheme-object
 * @example
 * {
 *   type: "oauth2",
 *   flows: {
 *     implicit: {
 *       authorizationUrl: "https://example.com/api/oauth/dialog",
 *       scopes: {
 *         "write:pets": "modify pets in your account",
 *         "read:pets": "read your pets"
 *       }
 *     }
 *   }
 * }
 */
export type SecuritySchemeObject = {

  /**
   * REQUIRED. The type of the security scheme. Valid values are `"apiKey"`, `"http"`, `"mutualTLS"`, `"oauth2"`, `"openIdConnect"`.
   */
  type: string

  /**
   * A description for security scheme. {@link https://spec.commonmark.org/ CommonMark syntax} MAY be used for rich text representation.
   */
  description?: string

  /**
   * REQUIRED. The name of the header, query or cookie parameter to be used.
   */
  name: string

  /**
   * REQUIRED. The location of the API key. Valid values are `"query"`, `"header"` or `"cookie"`.
   */
  in: 'query' | 'header' | 'cookie'

  /**
   * REQUIRED. The name of the HTTP Authorization scheme to be used in the Authorization header as defined in {@link https://spec.openapis.org/oas/v3.1.0#bib-RFC7235 [RFC7235]}. The values used SHOULD be registered in the {@link https://www.iana.org/assignments/http-authschemes/http-authschemes.xhtml IANA Authentication Scheme registry}.
   */
  scheme: string

  /**
   * A hint to the client to identify how the bearer token is formatted. Bearer tokens are usually generated by an authorization server, so this information is primarily for documentation purposes.
   */
  bearerFormat?: string

  /**
   * REQUIRED. An object containing configuration information for the flow types supported.
   */
  flows: OAuthFlowsObject

  /**
   * REQUIRED. OpenId Connect URL to discover OAuth2 configuration values. This MUST be in the form of a URL. The OpenID Connect standard requires the use of TLS.
   */
  openIdConnectUrl: string

} & Extension